# Generated by Django 4.2 on 2024-01-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adatbázismodell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szöveg', models.CharField(max_length=20)),
                ('szám', models.IntegerField()),
                ('boool', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'adatbázis adatok',
            },
        ),
    ]
