# Generated by Django 4.2 on 2024-04-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_felhasználó"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="felhasználó",
            name="név",
        ),
        migrations.AddField(
            model_name="felhasználó",
            name="e_mail",
            field=models.CharField(default="a", max_length=50),
            preserve_default=False,
        ),
    ]
